services:
  web:
    build: .
    ports:
      - '8007:8007'
    volumes:
      - ./workoutapp:/app
    environment:
      - PGSERVICEFILE=/app/.pg_service.conf
      - PGPASSFILE=/app/.pgpass
    env_file: 
      - .env
