# Generated by Django 4.0.2 on 2022-02-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('O', 'Outdoor'), ('I', 'Indoor')], max_length=1)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_distance', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('active_kilocalories', models.IntegerField()),
                ('elevation_gain', models.IntegerField(null=True)),
                ('total_kilocalories', models.IntegerField()),
                ('average_heart_rate', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('O', 'Outdoor'), ('I', 'Indoor')], max_length=1)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_distance', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('active_kilocalories', models.IntegerField()),
                ('elevation_gain', models.IntegerField(null=True)),
                ('total_kilocalories', models.IntegerField()),
                ('average_heart_rate', models.IntegerField()),
                ('average_cadence', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
