# Generated by Django 4.0.2 on 2022-03-04 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('O', 'Outdoor'), ('I', 'Indoor')], max_length=1)),
                ('start_time', models.DateTimeField(unique=True)),
                ('duration', models.DurationField()),
                ('active_kilocalories', models.IntegerField()),
                ('total_kilocalories', models.IntegerField()),
                ('average_heart_rate', models.IntegerField()),
                ('max_heart_rate', models.IntegerField()),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('elevation_gain', models.IntegerField(blank=True, null=True)),
                ('step_cadence', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flights_climbed', models.IntegerField(blank=True, null=True)),
                ('step_count', models.IntegerField(blank=True, null=True)),
                ('swim_cadence', models.IntegerField(blank=True, null=True)),
                ('total_swimming_stroke_count', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
