# Generated by Django 4.0.2 on 2022-02-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('O', 'Outdoor'), ('I', 'Indoor')], max_length=1)),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active_kilocalories', models.IntegerField()),
                ('elevation_gain', models.IntegerField(blank=True)),
                ('total_kilocalories', models.IntegerField()),
                ('average_heart_rate', models.IntegerField()),
                ('average_cadence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('O', 'Outdoor'), ('I', 'Indoor')], max_length=1)),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active_kilocalories', models.IntegerField()),
                ('elevation_gain', models.IntegerField(blank=True)),
                ('total_kilocalories', models.IntegerField()),
                ('average_heart_rate', models.IntegerField()),
            ],
        ),
    ]
