# Generated by Django 4.1.1 on 2023-11-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('set', models.IntegerField()),
                ('reps_to_do', models.CharField(max_length=10)),
                ('reps_done', models.CharField(max_length=10)),
                ('kg_to_do', models.CharField(max_length=10)),
                ('kg_done', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('intensity_string', models.CharField(max_length=100)),
                ('intensity', models.IntegerField()),
                ('duration', models.DurationField()),
                ('moves', models.IntegerField()),
                ('exercises', models.ManyToManyField(to='workouts.strengthexercise')),
            ],
        ),
    ]
