# Generated by Django 4.0.2 on 2022-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='actual_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walk',
            name='actual_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
