# Generated by Django 4.0.2 on 2022-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
