# Generated by Django 4.0.2 on 2022-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_run_actual_distance_walk_actual_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='actual_distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='elevation_gain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='actual_distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='elevation_gain',
            field=models.IntegerField(null=True),
        ),
    ]
