# Generated by Django 4.0.2 on 2022-02-27 13:57

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_run_actual_distance_alter_run_elevation_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walk',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
