# Generated by Django 4.0.2 on 2022-03-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_run_active_kilocalories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='average_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
