# Generated by Django 4.2.11 on 2024-04-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_vo2reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='mins_at_hr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
