# Generated by Django 4.0.2 on 2022-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_run_start_time_alter_walk_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='active_kilocalories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='total_kilocalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='active_kilocalories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walk',
            name='total_kilocalories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
