# Generated by Django 4.1.1 on 2023-11-12 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('set', models.IntegerField()),
                ('reps_to_do', models.CharField(max_length=10)),
                ('reps_done', models.CharField(max_length=10)),
                ('kg_to_do', models.CharField(max_length=10)),
                ('kg_done', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('intensity_string', models.CharField(max_length=100)),
                ('intensity', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('moves', models.IntegerField()),
                ('exercises', models.ManyToManyField(to='strength.strengthexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
